stages:
  - generate_files
  - compare
  - deploy
  - result

generate_files_jedi:
  id_tokens:
    SITE_ID_TOKEN:
      aud: "https://gitlab.jsc.fz-juelich.de"
  stage: generate_files
  rules:
    - when: manual # Manually triggered
      changes:
        - verification/**/* # all files under folder 'verification'
        - shared/**/* # all files under folder 'shared'
  tags:
    - jedi
    - login
  script:
    - ml JUBE
    - cd verification/
    - jube-autorun -r "-t jd gp cb_all cd_all" all_hello_reduced.xml
  artifacts:
    paths: 
      - verification/pin_logs/
    expire_in: "1 hour"

compare_pinning:
  stage: compare
  image: node:latest
  rules:
    - changes:
        - verification/**/* # all files under folder 'verification'
        - shared/**/* # all files under folder 'shared'
  tags:
    - public-docker
  script:
    - mv shared/javascripts/* verification/
    - cd verification/
    - echo 0 > exit_code.txt
    - node comparison.js pin_logs/ || echo $? > exit_code.txt
  artifacts:
    paths:
      - verification/results.json
      - verification/exit_code.txt
    expire_in: "1 hour"

pages:
  stage: deploy
  rules:
    - changes:
        - verification/**/* # all files under folder 'verification'
        - shared/**/* # all files under folder 'shared'
  script:
    - mv shared public
    - mv verification/results.json public/results.json
    - mv verification/pin_logs/ public/pin_logs/
    - mv verification/index.html public/index.html
    - mv verification/main.js public/javascripts/main.js
  artifacts:
    paths:
      - public/
    expire_in: "1 hour"
  
check:
  stage: result
  needs: 
    - job: compare_pinning
      artifacts: true
  rules:
    - changes:
        - verification/**/* # all files under folder 'verification'
        - shared/**/* # all files under folder 'shared'
  dependencies:
    - compare_pinning
  script:
    - exit_code=$(cat verification/exit_code.txt)
    - if [ "$exit_code" -ne 0 ]; then
        echo "Errors occurred during the comparison.";
        exit 1;
      fi

pages:production:
  stage: deploy
  needs: []
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"' # Only on the master branch
      when: manual # Manually triggered
      changes:
        - webtool/**/* # all files under folder 'webtool'
        - shared/**/* # all files under folder 'shared'
  script:
    - mv webtool/index.html shared/index.html
    - mv webtool/main.js shared/javascripts/main.js
    - echo "Deploying to production"
    - "sshpass -e -P 'passphrase for key' rsync -rlgoDzP --del shared/* apps_pinning_tool:"
  environment:
    name: production
    url: https://apps.fz-juelich.de/jsc/llview/pinning/
