stages:
  - generate_files
  - compare
  - deploy
  - result

generate_files_jusuf:
  id_tokens:
    SITE_ID_TOKEN:
      aud: "https://gitlab.jsc.fz-juelich.de"
  stage: generate_files
  tags:
    - jusuf
    - login
  script:
    - ml JUBE
    - cd verification/
    - jube-autorun -r "-t js gp cb_all cd_all" all_hello_reduced.xml
  artifacts:
    paths: 
      - verification/pin_logs/
    expire_in: "1 hour"

compare_pinning:
  stage: compare
  image: node:latest
  tags:
    - public-docker
  script:
    - cd webtool/javascripts/
    - mv $(ls | grep -v main.js) ../../verification/
    - cd ../../verification/
    - node comparison.js pin_logs/ || echo $? > exit_code.txt
  artifacts:
    paths:
      - verification/results.json
      - verification/exit_code.txt
    expire_in: "1 hour"

pages:
  stage: deploy
  script:
    - mkdir public/
    - mkdir public/javascripts/
    - mv verification/results.json public/results.json
    - mv verification/pin_logs/ public/pin_logs/
    - mv verification/index.html public/index.html
    - mv verification/main.js public/javascripts/main.js
    - mv webtool/images/ public/images/
    - mv webtool/stylesheets/ public/stylesheets/
    - cd webtool/javascripts/
    - mv $(ls | grep -v main.js) ../../public/javascripts/
  artifacts:
    paths:
      - public/
    expire_in: "1 hour"
  
check:
  stage: result
  dependencies:
    - compare_pinning
  script:
    - exit_code=$(cat verification/exit_code.txt)
    - if [ "$exit_code" -ne 0 ]; then
        echo "Errors occurred during the comparison.";
        exit 1;
      fi
